**Part1**

**Q1**

In [38]:
import pandas as pd
table = [[i,i,i] for i in range(1,4)]
pd_table = pd.DataFrame(table)
print(pd_table)

   0  1  2
0  1  1  1
1  2  2  2
2  3  3  3

**Q2**

In [39]:
for i in range(3):
  print("Row "+str(i)+":", table[i])

Row 0: [1, 1, 1]
Row 1: [2, 2, 2]
Row 2: [3, 3, 3]

Q3

In [40]:
for i in range(3):
  table[0][i] = -1
for i in range(3):
  print("Row "+str(i)+":", table[i])

Row 0: [-1, -1, -1]
Row 1: [2, 2, 2]
Row 2: [3, 3, 3]

**Q4**

In [41]:
for i in range(3):
  table[i][0] = -1
for i in range(3):
  print("Row "+str(i)+":", table[i])

Row 0: [-1, -1, -1]
Row 1: [-1, 2, 2]
Row 2: [-1, 3, 3]

**Q5**

In [42]:
def alignment_table(seq1,seq2):
  print("Seq 1: ",seq1," with lenth ",len(seq1))
  print("Seq 2: ",seq2," with lenth ",len(seq2))
  print("The initial table with dimention ",len(seq1)+1, " and ", len(seq2)+1," for the sequence alignment is: ")
  table = [[0]*(len(seq2)+1) for i in range(len(seq1)+1)]
  for i in range(len(seq1)+1):
    print("Row "+str(i)+":", table[i])
alignment_table("AATTATATT","ACGTTAT")

Seq 1:  AATTATATT  with lenth  9
Seq 2:  ACGTTAT  with lenth  7
The initial table with dimention  10  and  8  for the sequence alignment is:
Row 0: [0, 0, 0, 0, 0, 0, 0, 0]
Row 1: [0, 0, 0, 0, 0, 0, 0, 0]
Row 2: [0, 0, 0, 0, 0, 0, 0, 0]
Row 3: [0, 0, 0, 0, 0, 0, 0, 0]
Row 4: [0, 0, 0, 0, 0, 0, 0, 0]
Row 5: [0, 0, 0, 0, 0, 0, 0, 0]
Row 6: [0, 0, 0, 0, 0, 0, 0, 0]
Row 7: [0, 0, 0, 0, 0, 0, 0, 0]
Row 8: [0, 0, 0, 0, 0, 0, 0, 0]
Row 9: [0, 0, 0, 0, 0, 0, 0, 0]

**Q6**

In [51]:
def alignment_table_updated(seq1,seq2):
  import pandas as pd
  print("Seq 1: ",seq1," with lenth ",len(seq1))
  print("Seq 2: ",seq2," with lenth ",len(seq2))
  print("The initial table with dimention ",len(seq1)+1, " and ", len(seq2)+1," for the sequence alignment is: ")
  table = [[0]*(len(seq2)+1) for i in range(len(seq1)+1)]
  for i in range(len(seq2)+1): # update first row
    table[0][i] = table[0][i] -i
  for i in range(len(seq1)+1): # update first column
    table[i][0] = table[i][0] -i
  pd_table = pd.DataFrame(table)
  print(pd_table)

alignment_table_updated("AATTATATT","ACGTTAT")

Seq 1:  AATTATATT  with lenth  9
Seq 2:  ACGTTAT  with lenth  7
The initial table with dimention  10  and  8  for the sequence alignment is:
   0  1  2  3  4  5  6  7
0  0 -1 -2 -3 -4 -5 -6 -7
1 -1  0  0  0  0  0  0  0
2 -2  0  0  0  0  0  0  0
3 -3  0  0  0  0  0  0  0
4 -4  0  0  0  0  0  0  0
5 -5  0  0  0  0  0  0  0
6 -6  0  0  0  0  0  0  0
7 -7  0  0  0  0  0  0  0
8 -8  0  0  0  0  0  0  0
9 -9  0  0  0  0  0  0  0

**Part2**

In [54]:
def buildNWTable(seq1, seq2, match=1, mismatch=-1, gap=-1):
  import pandas as pd
  print('Seq1: ',seq1)
  print('Seq2: ',seq2)
  table = [[0]*(len(seq2)+1) for i in range(len(seq1)+1)] # create initial table with 0
  print("The initial alignment table is: ")
  pd_table = pd.DataFrame(table)
  print(pd_table)
  print("\n")
  for i in range(len(seq2)+1): # update first row
    table[0][i] = table[0][i] + mismatch *i
  for i in range(len(seq1)+1): # update first column
    table[i][0] = table[i][0] + mismatch *i

  for rowid in range (1,len(seq1)+1):
    for colid in range(1,len(seq2)+1):
      if seq1[rowid-1] == seq2[colid-1]:
        case1 = table[rowid-1][colid-1] + match
      else:
        case1 = table[rowid-1][colid-1] + mismatch

      case2 = table[rowid-1][colid]+gap

      case3 = table[rowid][colid-1]+gap

      table[rowid][colid] = max([case1,case2,case3])
  pd_table = pd.DataFrame(table)
  print("The final alignment table is:")
  print(pd_table)


buildNWTable("TTGCT","CTTCCT")

Seq1:  TTGCT
Seq2:  CTTCCT
The initial alignment table is:
   0  1  2  3  4  5  6
0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0


The final alignment table is:
   0  1  2  3  4  5  6
0  0 -1 -2 -3 -4 -5 -6
1 -1 -1  0 -1 -2 -3 -4
2 -2 -2  0  1  0 -1 -2
3 -3 -3 -1  0  0 -1 -2
4 -4 -2 -2 -1  1  1  0
5 -5 -3 -1 -1  0  0  2

In [55]:
buildNWTable("TTGCT","CTTCCT",match=2, mismatch=-2, gap=-2)

Seq1:  TTGCT
Seq2:  CTTCCT
The initial alignment table is:
   0  1  2  3  4  5  6
0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0


The final alignment table is:
    0  1  2  3  4   5   6
0   0 -2 -4 -6 -8 -10 -12
1  -2 -2  0 -2 -4  -6  -8
2  -4 -4  0  2  0  -2  -4
3  -6 -6 -2  0  0  -2  -4
4  -8 -4 -4 -2  2   2   0
5 -10 -6 -2 -2  0   0   4

In [56]:
buildNWTable("AAAGAC","TAAAGACA",match=1, mismatch=-1, gap=-1)

Seq1:  AAAGAC
Seq2:  TAAAGACA
The initial alignment table is:
   0  1  2  3  4  5  6  7  8
0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0


The final alignment table is:
   0  1  2  3  4  5  6  7  8
0  0 -1 -2 -3 -4 -5 -6 -7 -8
1 -1 -1  0 -1 -2 -3 -4 -5 -6
2 -2 -2  0  1  0 -1 -2 -3 -4
3 -3 -3 -1  1  2  1  0 -1 -2
4 -4 -4 -2  0  1  3  2  1  0
5 -5 -5 -3 -1  1  2  4  3  2
6 -6 -6 -4 -2  0  1  3  5  4

**Part3**

In [47]:
def NWTraceBack(seq1, seq2, match=1, mismatch=-1, gap=-1):
  import pandas as pd
  print('Seq1: ',seq1)
  print('Seq2: ',seq2,"\n")
  table = [[0]*(len(seq2)+1) for i in range(len(seq1)+1)] # create initial table with 0
  print("The initial alignment table is: ")
  pd_table = pd.DataFrame(table)
  print(pd_table)
  print("\n")

# ## start update the first column and the first row

  for i in range(len(seq2)+1): # update first row
    table[0][i] = table[0][i] + mismatch *i
  for i in range(len(seq1)+1): # update first column
    table[i][0] = table[i][0] + mismatch *i
  
## build the alignment table

  for rowid in range (1,len(seq1)+1):
    for colid in range(1,len(seq2)+1):
      if seq1[rowid-1] == seq2[colid-1]:
        case1 = table[rowid-1][colid-1] + match
      else:
        case1 = table[rowid-1][colid-1] + mismatch

      case2 = table[rowid-1][colid]+gap

      case3 = table[rowid][colid-1]+gap

      table[rowid][colid] = max([case1,case2,case3])
  print("The final alignment table is:")
  pd_table = pd.DataFrame(table)
  print(pd_table)
  print("\n")

## the best alignmnet
  
  col_start = len(seq2)
  row_start = len(seq1)
  list1=[]
  blank=[]
  list2=[]
  while col_start > 0 or row_start > 0:
    if seq1[row_start-1] == seq2[col_start-1]:
      case1 = table[row_start - 1][col_start - 1] + match
    else:
      case1 = table[row_start - 1][col_start - 1] + mismatch

    case2 = table[row_start - 1][col_start] + gap

    case3 = table[row_start][col_start - 1] + gap


    if case1 == table[row_start][col_start]:
      list1.insert(0,seq1[row_start-1])
      list2.insert(0,seq2[col_start-1])
      row_start -=1
      col_start -=1

    elif case2 == table[row_start][col_start]: # top 2 bottom
      list1.insert(0,seq1[row_start-1])
      list2.insert(0,"-")
      row_start -=1
    
    elif case3 == table[row_start][col_start]: # left 2 right
      list1.insert(0,"-")
      list2.insert(0,seq2[col_start-1])
      col_start -=1
  for i in range(len(list2)):
    if list1[i] == list2[i]:
      blank.append("|")
    else:
      blank.append(' ')
  print("The best alignmnet is: ")
  print(*list1)
  print(*blank)
  print(*list2)
  print("\n")
## best alignment socre

  print("The score of optimal alignment is: ",table[len(seq1)][len(seq2)])

In [48]:
NWTraceBack('TTGCT', 'CTTCCT')

Seq1:  TTGCT
Seq2:  CTTCCT

The initial alignment table is:
   0  1  2  3  4  5  6
0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0


The final alignment table is:
   0  1  2  3  4  5  6
0  0 -1 -2 -3 -4 -5 -6
1 -1 -1  0 -1 -2 -3 -4
2 -2 -2  0  1  0 -1 -2
3 -3 -3 -1  0  0 -1 -2
4 -4 -2 -2 -1  1  1  0
5 -5 -3 -1 -1  0  0  2


The best alignmnet is:
- T T G C T
  | |   | |
C T T C C T


The score of optimal alignment is:  2

In [49]:
NWTraceBack("AAAGAC","TAAAGACA")

Seq1:  AAAGAC
Seq2:  TAAAGACA

The initial alignment table is:
   0  1  2  3  4  5  6  7  8
0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0


The final alignment table is:
   0  1  2  3  4  5  6  7  8
0  0 -1 -2 -3 -4 -5 -6 -7 -8
1 -1 -1  0 -1 -2 -3 -4 -5 -6
2 -2 -2  0  1  0 -1 -2 -3 -4
3 -3 -3 -1  1  2  1  0 -1 -2
4 -4 -4 -2  0  1  3  2  1  0
5 -5 -5 -3 -1  1  2  4  3  2
6 -6 -6 -4 -2  0  1  3  5  4


The best alignmnet is:
- A A A G A C -
  | | | | | |
T A A A G A C A


The score of optimal alignment is:  4